# 국세청의 사업자등록정보 상태조회 서비스 호출 설정 파일 입니다. (호출시 인증키 필수)
external:
  nts:
    base-url: https://api.odcloud.kr/api/nts-businessman/v1/status # 사업자 등록 상태조회 API 주소
    serviceKey: ${serviceKey} # 인증키
    connect-timeout: 5000 # RestTemplate 으로 서버 연결 대기시간(5초)
    read-timeout: 5000 # RestTemplate 으로 응답 대기시간(5초)