spring:
  config:
    activate:
      on-profile: dev
  profiles:
    include: smtp, oauth
  application:
    name: onharu

  # 데이터소스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA 설정
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: ${JPA_FORMAT_SQL}
        highlight_sql: ${JPA_HIGHLIGHT_SQL}

# MinIO 설정 (로컬 개발용)
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  region: ${MINIO_REGION:us-east-1}
  bucket: ${MINIO_BUCKET:onharu-minio}

# 서버 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    root: INFO
    com.backend.onharu: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOGGING_FILE_NAME:/app/logs/onharu.log}
    max-size: 10MB
    max-history: 30